language: generic
sudo: required
services:
  -docker

before_install:
  - docker build -t moraruv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true moraruv/react-test npm test

after_success:
  - docker build -t moraruv/multi-client ./client
  - docker build -t moraruv/multi-nginx ./nginx
  - docker build -t moraruv/multi-server ./server
  - docker build -t moraruv/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push moraruv/multi-client
  - docker push moraruv/multi-nginx
  - docker push moraruv/multi-server
  - docker push moraruv/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-526225328477
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
    